//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcmTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRQ_CHG_WO_StatusType
    {
        public int CRQ_CHG_WO_TypeID { get; set; }
        public string CRQ_CHG_WO_TypeName { get; set; }
    }
}
