//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcmTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_ExecutionList_new_CT
    {
        public byte[] C___start_lsn { get; set; }
        public byte[] C___end_lsn { get; set; }
        public byte[] C___seqval { get; set; }
        public int C___operation { get; set; }
        public byte[] C___update_mask { get; set; }
        public Nullable<int> lcmID { get; set; }
        public Nullable<int> resourceID { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<int> groupingID { get; set; }
        public Nullable<int> workOrderID { get; set; }
        public string WO_StatusID { get; set; }
        public string currentServerName { get; set; }
        public Nullable<int> cmo { get; set; }
        public string newServerName { get; set; }
        public Nullable<int> fmo { get; set; }
        public Nullable<System.DateTime> status27Date { get; set; }
        public string notes { get; set; }
        public string waveNum { get; set; }
        public Nullable<System.DateTime> handoverDate { get; set; }
        public string region { get; set; }
        public string country { get; set; }
        public Nullable<int> siteID { get; set; }
        public string siteComments { get; set; }
        public string appName { get; set; }
        public string appOwner { get; set; }
        public string monsantoPM { get; set; }
        public string atosPM { get; set; }
        public string escalationNotes { get; set; }
        public string personContacted { get; set; }
        public Nullable<System.DateTime> contactedDate { get; set; }
        public string serialNum { get; set; }
        public string pmNotes { get; set; }
        public Nullable<int> environmentID { get; set; }
        public Nullable<int> supportGroupID { get; set; }
        public Nullable<int> operatingSystemID { get; set; }
        public string skyfall { get; set; }
        public Nullable<int> skyfallNum { get; set; }
        public Nullable<decimal> skyfall_index { get; set; }
        public Nullable<int> AtosTeamID { get; set; }
        public Nullable<int> decomTypeID { get; set; }
        public Nullable<System.DateTime> decomStartDate { get; set; }
        public string retirementCrq { get; set; }
        public string retirementChg { get; set; }
        public string retirementWo { get; set; }
        public Nullable<bool> j_data_decom_only { get; set; }
        public Nullable<System.DateTime> forecastedStatusDate { get; set; }
        public Nullable<System.DateTime> cabApprovalDate { get; set; }
        public Nullable<int> databaseTypeID { get; set; }
        public string java { get; set; }
        public string middleware { get; set; }
        public string citrix { get; set; }
        public Nullable<int> lcmWeek { get; set; }
        public string platforms { get; set; }
        public string complianceAssetID { get; set; }
        public string screamTeast { get; set; }
        public Nullable<int> serverInCorral_ID { get; set; }
        public Nullable<int> plannedDispositionID { get; set; }
        public Nullable<System.DateTime> AppTeamTurnoverDate { get; set; }
        public string managedBy { get; set; }
        public Nullable<int> currentOsVersion { get; set; }
        public Nullable<int> futureOsVersion { get; set; }
        public Nullable<System.DateTime> dateEnteredCorral { get; set; }
        public string followupMonth { get; set; }
        public string transformation { get; set; }
        public string afqOsVersion { get; set; }
        public Nullable<int> fiscalYear { get; set; }
        public Nullable<bool> NZEV_Overlap { get; set; }
        public string serverRequiresOsLicense { get; set; }
        public Nullable<int> NumCores { get; set; }
        public Nullable<int> NumProcessors { get; set; }
        public string NZEV_Remediation_Planned { get; set; }
        public string ISO_Exception_Number { get; set; }
        public Nullable<bool> COG_Supported { get; set; }
        public Nullable<int> countryRegionID { get; set; }
        public Nullable<int> C___command_id { get; set; }
    }
}
