//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcmTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalsTarget
    {
        public int GoalsTargetsID { get; set; }
        public string GoalsTargetsName { get; set; }
        public int GoalsTargetsNum { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
