//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcmTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LifecycleManagementEntities : DbContext
    {
        public LifecycleManagementEntities()
            : base("name=LifecycleManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<captured_columns> captured_columns { get; set; }
        public virtual DbSet<change_tables> change_tables { get; set; }
        public virtual DbSet<ddl_history> ddl_history { get; set; }
        public virtual DbSet<index_columns> index_columns { get; set; }
        public virtual DbSet<lsn_time_mapping> lsn_time_mapping { get; set; }
        public virtual DbSet<AssignedResource> AssignedResources { get; set; }
        public virtual DbSet<AtosTeam> AtosTeams { get; set; }
        public virtual DbSet<CmoFmoType> CmoFmoTypes { get; set; }
        public virtual DbSet<CorralPlannedDisposition> CorralPlannedDispositions { get; set; }
        public virtual DbSet<CountryRegion> CountryRegions { get; set; }
        public virtual DbSet<CRQ_CHG_WO_StatusType> CRQ_CHG_WO_StatusType { get; set; }
        public virtual DbSet<DatabaseType> DatabaseTypes { get; set; }
        public virtual DbSet<DecomType> DecomTypes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Environment> Environments { get; set; }
        public virtual DbSet<EventLog> EventLogs { get; set; }
        public virtual DbSet<EventLog1> EventLogs1 { get; set; }
        public virtual DbSet<ExecutionList> ExecutionLists { get; set; }
        public virtual DbSet<ExecutionList_new> ExecutionList_new { get; set; }
        public virtual DbSet<FollowupMonth> FollowupMonths { get; set; }
        public virtual DbSet<GoalsTarget> GoalsTargets { get; set; }
        public virtual DbSet<Grouping> Groupings { get; set; }
        public virtual DbSet<GroupingsType> GroupingsTypes { get; set; }
        public virtual DbSet<InCorralType> InCorralTypes { get; set; }
        public virtual DbSet<OperatingSystem> OperatingSystems { get; set; }
        public virtual DbSet<OperatingSystemVersion> OperatingSystemVersions { get; set; }
        public virtual DbSet<PlannedDispositionType> PlannedDispositionTypes { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<PlatformsType> PlatformsTypes { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ScreamTestType> ScreamTestTypes { get; set; }
        public virtual DbSet<ServerInCorral> ServerInCorrals { get; set; }
        public virtual DbSet<ServersInCorralType> ServersInCorralTypes { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<StatusesType> StatusesTypes { get; set; }
        public virtual DbSet<StatusHistory> StatusHistories { get; set; }
        public virtual DbSet<StatusHistoryArchive> StatusHistoryArchives { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<SupportGroupCmdb> SupportGroupCmdbs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<WorkOrderReason> WorkOrderReasons { get; set; }
        public virtual DbSet<WorkOrderStatu> WorkOrderStatus { get; set; }
        public virtual DbSet<dbo_ExecutionList_CT> dbo_ExecutionList_CT { get; set; }
        public virtual DbSet<dbo_ExecutionList_new_CT> dbo_ExecutionList_new_CT { get; set; }
        public virtual DbSet<systranschema> systranschemas { get; set; }
    }
}
