//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LcmTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusHistory
    {
        public int statusHistoryID { get; set; }
        public int statusID { get; set; }
        public int lcmID { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
    
        public virtual ExecutionList_new ExecutionList_new { get; set; }
        public virtual StatusHistoryArchive StatusHistoryArchive { get; set; }
    }
}
